### ISSUE TITLE
Formatting failed when running mvim with MIX_ENV=edit

### ISSUE THREAD

**Issue by lukashambsch** [mhinz/vim-mix-format#15]
Thanks for the great plugin! I've had one small issue when using it.

I always try to open vim w/ `MIX_ENV=edit mvim .` so that the auto reloading on the server will work correctly. When I use this plugin w/ that enabled, I get a the `Formatting failed.` message. However it works fine when I open normally w/ `mvim .`.

Please let me know if I can provide any extra info.

**Comment by mhinz** [comment]
You mean `MIX_ENV=dev`? :)

If not so, does `MIX_ENV=edit mix format --check-equivalent path/to/file` work in the shell?

**Comment by lukashambsch** [comment]
No, I mean edit. I'm not sure if that's correct or not, but it works for the hot reloading. `MIX_ENV=edit mix format --check-equivalent path/to/file` doesn't work since there isn't an edit config file.

I'm not sure why running w/ `MIX_ENV=edit` fixes the hot reloading. It was suggested here: https://elixirforum.com/t/vim-interfering-with-phoenix-recompile-after-saving/10039/8.

**Comment by mhinz** [comment]
I see. After reading [this](https://github.com/phoenixframework/phoenix_live_reload/issues/70) and your link I now understand why you're using `MIX_ENV=edit` in the first place.

Whatever the root issue is, I can't reproduce it on macOS Mojave. The hot reloading works without any trick, so I never encountered that problem. I guess it's not too common, otherwise more people would have complained about it already.

Since I can't reproduce it myself, it's somewhat hard to come up with a fix.

Please try these two things:

1. Change [this line](https://github.com/mhinz/vim-mix-format/blob/ee602a459eea767b3aabc2d0061616146fe2a5f2/ftplugin/elixir.vim#L121) to just `return cmd`. Does it make any difference?
1. Change [the same line again](https://github.com/mhinz/vim-mix-format/blob/ee602a459eea767b3aabc2d0061616146fe2a5f2/ftplugin/elixir.vim#L121) to `return ['MIX_ENV=dev', 'sh', '-c', cmd]`. Does it make any difference?

**Comment by lukashambsch** [comment]
Neither of those two things made a difference. I really appreciate you taking a look at it, but it probably isn't worth any more of your time if you can't reproduce it.

Thanks again!

**Comment by mhinz** [comment]
Hmm, I wonder if there is anything I can even do from the plugin's side.. :\

When using `MIX_ENV=edit nvim`, all child processes started by the editor, and this involves this plugin's `mix format..`, will use `MIX_ENV=edit` as well. In my case that works, in yours it doesn't.

So, when `MIX_ENV=edit` makes a difference for `:MixFormat` in your case, then let's clear the environment off $MIX_ENV before we run `mix format...` in the plugin:

Please change once again [this line](https://github.com/mhinz/vim-mix-format/blob/ee602a459eea767b3aabc2d0061616146fe2a5f2/ftplugin/elixir.vim#L121) to `return ['env', '-u', 'MIX_ENV', 'sh', '-c', cmd]`. In theory the plugin should then act as if it was started with just `nvim`, not `MIX_ENV=edit nvim`.

**Comment by EQuimper** [comment]
I get the same exact problem, I need to use `MIX_ENV=edit` to let phoenix reload cause of ALE plugin. But because of this MixFormat don't work anymore.

**Comment by EQuimper** [comment]
@mhinz Your fix with the `['env', '-u', 'MIX_ENV', 'sh', '-c', cmd]` work for me thanks

**Comment by mhinz** [comment]
@EQuimper 

Awesome. Thanks for the feedback. ✨ I've added that workaround to master.
