### ISSUE TITLE
MixFormatDiff folding

### ISSUE THREAD

**Issue by habamax** [mhinz/vim-mix-format#18]
Could you tell me if diff should fold unchanged text or it shouldn't? Thanks!

![image](https://user-images.githubusercontent.com/234774/49566042-630cc200-f93a-11e8-9b0d-405b0ee346dc.png)

**Comment by habamax** [comment]
Well, If after `MixFormatDiff` command I issue `diffthis` I get what I need :)

![image](https://user-images.githubusercontent.com/234774/49566295-39a06600-f93b-11e8-953c-e78953c4186c.png)

Is this my setup lacks this last command call within `MixFormatDiff` or this is intended behaviour -- I and other users of `MixFormatDiff` should manually `diffthis` if needed?

**Comment by habamax** [comment]
Ok, this could be solved by the User autocmd:

    autocmd User MixFormatDiff diffthis | wincmd p | diffthis

**Comment by habamax** [comment]
Just a question though, is it intended behavior and we should use autocmd?

**Comment by mhinz** [comment]
Hmm, by that time `:diffthis` was done for both buffers already (you can check with `:set diff?`). The behaviour you see is caused by [this commit](https://github.com/mhinz/vim-mix-format/commit/09c6540).

It's a bad commit. I can't remember why I did this and the commit doesn't say so. :\

I revert it for now!

**Comment by habamax** [comment]
Thx!
