### ISSUE TITLE
Unable to redo changes

### ISSUE THREAD

**Issue by lukashambsch** [mhinz/vim-mix-format#20]
I have the plugin working with `MIX_ENV=edit mvim` (thanks for fixing that issue). But I'm seeing some strange behavior with redoing changes.

I have the plugin formatting on save and I'm able to undo previous changes, but I don't seem to be able to redo changes.

I noticed [this](https://github.com/mhinz/vim-mix-format/issues/13), but it seems a bit different.

**Comment by mhinz** [comment]
What is the strange behaviour you're seeing?

Can you please give the exact steps? I can't really reproduce it so far.

Maybe it's just that you got into a certain branch of the undo tree: `:h undo-tree`. FWIW, [undotree](https://github.com/mbbill/undotree) is a nice way to visualize the undo tree on the fly!

**Comment by lukashambsch** [comment]
I'm not able to reproduce it now. It must have been something I was doing. Sorry for wasting your time.

Undotree looks pretty cool! I'll check it out, thanks!

**Comment by lukashambsch** [comment]
Maybe I'm not losing my mind. I've captured a screen share I can send you if it'd be helpful. It's saying it's already at the newest changes when it should be able to redo the changes I made previously.

For example:

This line
```
testing + (blah.blah_blah_blah || 0) / (blah.blah_blah_blah_blah || 1) * (blah.blah_blah_blah || 1)
```
is reformatted to this
```
testing +
      (blah.blah_blah_blah || 0) / (blah.blah_blah_blah_blah || 1) * (blah.blah_blah_blah || 1)
```

Then when I undo those changes and save, I'm not able to redo them again.

I hope that helps.

**Comment by mhinz** [comment]
Yup, that's exactly how the undo tree works. :-)

Using your example above:

- You have the original line. This is node 0 in the tree.
- Then you save which triggers the plugin which formats the line. This is node 1.
- When you now undo, you're back at node 0.
- You save again which runs the formatter and the line is changed again. Now you branch off node 0 and create a new node 2.

At this state, redo won't be possible anymore, because your at the leaf end of your branch already. There is nothing to redo. Undo would go back to node 0.

What you want, is to go back to the branch of node 1 again, which you can with `:undo 1`. (It's easy to find the right branch with the undotree plugin.)

Also see `:h 32.2` and `:h 32.3` which explains this with a bit of ASCII art.

**Comment by lukashambsch** [comment]
Ohh, got it. The plugin's change counts in the undo tree, so you can't redo the previous changes w/ the normal command.

I was thinking the plugin's changes wouldn't actually be a part of the undo tree. Thanks for the explanation.
