### ISSUE TITLE
Press ENTER or type command to continue

### ISSUE THREAD

**Issue by chalmagean** [mhinz/vim-mix-format#22]
I have set the format on save, and everytime there's work for the formatter, I get this message: "Press ENTER or type command to continue". How do I get rid of it?

**Comment by mhinz** [comment]
And there's nothing echoed above the `Press ENTER` line? Vim usually prompts when a message in the echo area is longer than the width of the window.

- Does it only happen when you have a very long filename? Or in a small Vim window?
- Does the prompt disappear after `:set shortmess+=F`?

**Comment by chalmagean** [comment]
No, the filename is not long (see the screenshot). The window is not small either.
The message doesn't disappear after `:set shortmess+=F`

![2019-04-26 at 13 17](https://user-images.githubusercontent.com/8421/56801370-f54c2e80-6825-11e9-9650-47250d8b04ff.png)

**Comment by mhinz** [comment]
I think the problem is that, for some reason, the filename gets written twice?

Just for testing, the prompt doesn't appear with `:set cmdheight=2`, right?

- Then we have to find out why it's written twice. It could also be written once by two separate plugins. Maybe check `:au BufWrite` and `:au BufWritePre` for clues. (Or disable all other plugins during testing.)
- Does it help if you include `silent` in front of the `update` here? https://github.com/mhinz/vim-mix-format/blob/master/ftplugin/elixir.vim#L205 Although it shouldn't make a difference when `shortmess+=F` isn't working.

**Comment by chalmagean** [comment]
If I set `cmdheight=2` the prompt does not appear.

And `silent` does fix the issue.

![2019-04-26 at 13 52](https://user-images.githubusercontent.com/8421/56803116-83c2af00-682a-11e9-8851-44c3e58dbbae.png)
![2019-04-26 at 13 51](https://user-images.githubusercontent.com/8421/56803117-83c2af00-682a-11e9-9a88-f9c235595283.png)

**Comment by mhinz** [comment]
Okay, I pushed the `silent` fix.

Thanks for reporting this! ✨

**Comment by chalmagean** [comment]
Awesome, thank you.
