### ISSUE TITLE
Doesn't Work with Vim 8's New Package Feature

### ISSUE THREAD

**Issue by candyapplecorn** [mhinz/vim-mix-format#24]
Hello, I'm on a MacBook, using this Vim version:

> vim --version
> VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov 29 2017 18:37:46)

I ran:

`git clone https://github.com/mhinz/vim-mix-format.git ~/.vim/pack/my-packages/start/vim-mix-format`

Then I opened a _some-elixir-file.exs_ in Vim and tried **:MixFormat**. I got this:

**E492: Not an editor command: MixFormat**

**Comment by mhinz** [comment]
My guess is that the `elixir` filetype was never set. Vim _still_ sets the filetype to `euphoria3` (whatever that is) instead of `elixir` for `.ex` and `.exs` files.

I suggest to also install vim-elixir:

```
git clone https://github.com/elixir-editors/vim-elixir ~/.vim/pack/my-packages/start/vim-elixir
```

If you don't want to install `vim-elixir`, you could put this in your vimrc instead:

```vim
autocmd BufNewFile,BufRead *.ex{,s} set filetype=elixir
```

Does this solve the problem?

**Comment by candyapplecorn** [comment]
Hi @mhinz , thanks for getting back to me so quickly. 
I already had vim-elixir installed, and I added your code snippet to my .vimrc. 
No changes on my end. 
At this point, I believe it's a problem with my environment/setup, and not vim-mix-format. I'll figure it out eventually - that's what professionals do ;)

**Comment by mhinz** [comment]
Okay, feel free to ask further question in here. FWIW, I tested with your _exact_ commad and it worked for me (`:scriptnames` shows `.../vim-mix-format/ftplugin/elixir.vim` as sourced).

Or maybe you just happen to have a broken Vim version. Happens every now and then (since its development is still rapid). :)
