### ISSUE TITLE
let g:mix_format_on_save = 1 does not work with :wa

### ISSUE THREAD

**Issue by vais** [mhinz/vim-mix-format#26]
`let g:mix_format_on_save = 1` does not work with `:wa[ll]` i.e. only the active buffer gets formatted, but any other modified buffers simply get saved. Is this by design? Is there any way to format all modified buffers on save?

**Comment by mhinz** [comment]
Unfortunately Vim emits the `BufWritePre` every time the current buffer gets saved. It doesn't say anything about other buffers. That's why the plugin is designed to work on the current buffer only.

So, it would probably be best to just run `mix format` in the shell for the whole project in such cases.

The only workaround I can think of would be simply cycling through all modified buffers in the current window and save the buffer. Or even shorter: `:bufdo if &modified | write | endif`. Never tried it though.

**Comment by vais** [comment]
Marco, thank you for taking the time to explain, makes sense!
