### ISSUE TITLE
After run format, the cursor would jump to the start of the line.

### ISSUE THREAD

**Issue by ChrisZou** [mhinz/vim-mix-format#3]
After run `:MixFormat`, the cursor would jump to the start of the line.
My env:
macOS High Sierra, 10.13.1
neovim 0.2.2

**Comment by mhinz** [comment]
Does it _always_ happen?

What about this one-line file:

```elixir
IO.puts "foo"
```

`:MixFormat` should put parentheses around the string _without_ moving the cursor.

**Comment by ChrisZou** [comment]
@mhinz Sorry for being so late.
Yes, it always happens. I tried your one-line file suggestion above and yes, parentheses were put around the string, but the cursor was moved to the beginning of the line again.

**Comment by mhinz** [comment]
~~Hmm.~~

~~I wonder if another plugin is interfering somehow. Is `:noau MixFormat` working as expected? If so, does a simple `:edit!` make the cursor jump back to the beginning of the line as well? ([Used here.](https://github.com/mhinz/vim-mix-format/blob/33325e6997da734ee3de1fdf79cbc983cd65483a/ftplugin/elixir.vim#L53))~~

EDIT: Oops. I found the culprit. It's because I set this: `:h 'nosol'`.

**Comment by mhinz** [comment]
It should work now. Thanks for bringing this up! ✨
